name: 08a - Control de flujo - matriz
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
        version: [18, 20]
        exclude:
        - os: ubuntu-22.04
          version: 20
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - if: matrix.os == 'ubuntu-22.04' && matrix.version == 20
        run: exit 1
        continue-on-error: true
      - run: npm ci
      - run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: despliegue
        run: echo "Desplegando en AWS..." 