name: 10a - entornos
on:
  push:
    branches:
      - main
      - releases/*
  workflow_dispatch:
jobs:
  entornos:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Verificar variable
        run: echo "${{vars.UNA_VARIABLE}}"
      - name: Verificar secreto
        run: echo "${{secrets.UN_SECRETO}}"